# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["kendell.r@outlook.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-empty"
description = ""
language = "javascript"
manifest_version = 3
name = "hifastlyjs"
service_id = "TNKG1CCMsHIgJODNaMvyCW"

[local_server]

[scripts]
  build = "npm run build"
  post_init = "npm install"
