name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check source code
        run: |
          yarn lint
          yarn prettier:check
          yarn copy:paste:detector
      - name: Compile source code
        run: yarn compile
      - name: Run tests
        run: yarn test:unit:coverage
