(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},m=ca(this),da="function"==
typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ea=function(a,b){if(b){var c=m;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Promise",function(a){function b(){this.a=null}function c(f){return f instanceof e?f:new e(function(h){h(f)})}if(a)return a;b.prototype.b=function(f){if(null==this.a){this.a=[];var h=this;this.c(function(){h.g()})}this.a.push(f)};var d=m.setTimeout;b.prototype.c=function(f){d(f,0)};b.prototype.g=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var h=0;h<f.length;++h){var k=f[h];f[h]=null;try{k()}catch(l){this.f(l)}}}this.a=null};b.prototype.f=function(f){this.c(function(){throw f;
})};var e=function(f){this.b=0;this.c=void 0;this.a=[];var h=this.f();try{f(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.f=function(){function f(l){return function(q){k||(k=!0,l.call(h,q))}}var h=this,k=!1;return{resolve:f(this.o),reject:f(this.g)}};e.prototype.o=function(f){if(f===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof e)this.s(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.l(f):
this.h(f)}};e.prototype.l=function(f){var h=void 0;try{h=f.then}catch(k){this.g(k);return}"function"==typeof h?this.v(h,f):this.h(f)};e.prototype.g=function(f){this.i(2,f)};e.prototype.h=function(f){this.i(1,f)};e.prototype.i=function(f,h){if(0!=this.b)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.b);this.b=f;this.c=h;this.j()};e.prototype.j=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)g.b(this.a[f]);this.a=null}};var g=new b;e.prototype.s=function(f){var h=
this.f();f.B(h.resolve,h.reject)};e.prototype.v=function(f,h){var k=this.f();try{f.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(f,h){function k(t,C){return"function"==typeof t?function(U){try{l(t(U))}catch(V){q(V)}}:C}var l,q,w=new e(function(t,C){l=t;q=C});this.B(k(f,l),k(h,q));return w};e.prototype.catch=function(f){return this.then(void 0,f)};e.prototype.B=function(f,h){function k(){switch(l.b){case 1:f(l.c);break;case 2:h(l.c);break;default:throw Error("Unexpected state: "+
l.b);}}var l=this;null==this.a?g.b(k):this.a.push(k)};e.resolve=c;e.reject=function(f){return new e(function(h,k){k(f)})};e.race=function(f){return new e(function(h,k){for(var l=ba(f),q=l.next();!q.done;q=l.next())c(q.value).B(h,k)})};e.all=function(f){var h=ba(f),k=h.next();return k.done?c([]):new e(function(l,q){function w(U){return function(V){t[U]=V;C--;0==C&&l(t)}}var t=[],C=0;do t.push(void 0),C++,c(k.value).B(w(t.length-1),q),k=h.next();while(!k.done)})};return e});
var fa=function(){fa=function(){};m.Symbol||(m.Symbol=ja)},ka=function(a,b){this.a=a;da(this,"description",{configurable:!0,writable:!0,value:b})};ka.prototype.toString=function(){return this.a};
var ja=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ka("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}(),ma=function(){fa();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&da(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return la(aa(this))}});ma=function(){}},la=function(a){ma();a={next:a};a[m.Symbol.iterator]=function(){return this};return a},
na=function(){this.f=!1;this.b=null;this.h=void 0;this.a=1;this.i=0;this.c=null},oa=function(a){if(a.f)throw new TypeError("Generator is already running");a.f=!0};na.prototype.g=function(a){this.h=a};var pa=function(a,b){a.c={Z:b,ga:!0};a.a=a.i};na.prototype.return=function(a){this.c={return:a};this.a=this.i};
var n=function(a,b,c){a.a=c;return{value:b}},qa=function(a){this.a=new na;this.b=a},ta=function(a,b){oa(a.a);var c=a.a.b;if(c)return ra(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return sa(a)},ra=function(a,b,c,d){try{var e=b.call(a.a.b,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.a.f=!1,e;var g=e.value}catch(f){return a.a.b=null,pa(a.a,f),sa(a)}a.a.b=null;d.call(a.a,g);return sa(a)},
sa=function(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.f=!1,{value:b.value,done:!1}}catch(c){a.a.h=void 0,pa(a.a,c)}a.a.f=!1;if(a.a.c){b=a.a.c;a.a.c=null;if(b.ga)throw b.Z;return{value:b.return,done:!0}}return{value:void 0,done:!0}},ua=function(a){this.next=function(b){oa(a.a);a.a.b?b=ra(a,a.a.b.next,b,a.a.g):(a.a.g(b),b=sa(a));return b};this.throw=function(b){oa(a.a);a.a.b?b=ra(a,a.a.b["throw"],b,a.a.g):(pa(a.a,b),b=sa(a));return b};this.return=function(b){return ta(a,b)};ma();this[Symbol.iterator]=
function(){return this}},Aa=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})},r=function(a){return Aa(new ua(new qa(a)))};
ea("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this+"";b+="";var e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<g&&c<e;)if(d[c++]!=b[f++])return!1;return f>=g}});
var Ba=Ba||{},u=this||self,Ca=function(){},Da=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},v=function(a){return"function"==Da(a)},Ea=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},Fa=function(a,b,c){return a.call.apply(a.bind,arguments)},Ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,
d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?x=Fa:x=Ga;return x.apply(null,arguments)},Ha=Date.now||function(){return+new Date},Ia=function(a,b){a=a.split(".");var c=u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},y=function(a,b){function c(){}
c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c;a.prototype.constructor=a};var Ja=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,Ja);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};y(Ja,Error);Ja.prototype.name="CustomError";var Ka;var La=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");Ja.call(this,c+a[d])};y(La,Ja);La.prototype.name="AssertionError";
var Ma=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var g=d}else a&&(e+=": "+a,g=b);throw new La(""+e,g||[]);},z=function(a,b,c){a||Ma("",null,b,Array.prototype.slice.call(arguments,2));return a},Na=function(a,b){throw new La("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},Oa=function(a,b,c){"number"!==typeof a&&Ma("Expected number but got %s: %s.",[Da(a),a],b,Array.prototype.slice.call(arguments,2));return a};var Pa=Array.prototype.indexOf?function(a,b){z(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Qa=Array.prototype.forEach?function(a,b,c){z(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},Sa=function(a){a:{var b=
Ra;for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]},Ta=function(a,b){b=Pa(a,b);var c;if(c=0<=b)z(null!=a.length),Array.prototype.splice.call(a,b,1);return c},fb=function(a){return Array.prototype.concat.apply([],arguments)},gb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var hb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),ib=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<hb.length;g++)c=hb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var A=function(a,b){this.c=a===jb&&b||"";this.f=kb};A.prototype.b=!0;A.prototype.a=function(){return this.c};A.prototype.toString=function(){return"Const{"+this.c+"}"};var lb=function(a){if(a instanceof A&&a.constructor===A&&a.f===kb)return a.c;Na("expected object of type Const, got '"+a+"'");return"type_error:Const"},kb={},jb={};var B=function(a,b){this.c=a===mb&&b||"";this.f=nb};B.prototype.b=!0;B.prototype.a=function(){return this.c.toString()};B.prototype.toString=function(){return"TrustedResourceUrl{"+this.c+"}"};
var qb=function(a,b){var c=lb(a);if(!ob.test(c))throw Error("Invalid TrustedResourceUrl format: "+c);a=c.replace(pb,function(d,e){if(!Object.prototype.hasOwnProperty.call(b,e))throw Error('Found marker, "'+e+'", in format string, "'+c+'", but no valid label mapping found in args: '+JSON.stringify(b));d=b[e];return d instanceof A?lb(d):encodeURIComponent(String(d))});return new B(mb,a)},pb=/%{(\w+)}/g,ob=/^((https:)?\/\/[0-9a-z.:[\]-]+\/|\/[^/\\]|[^:/\\%]+\/|[^:/\\%]*[?#]|about:blank#)/i,rb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,
tb=function(a,b,c){a=qb(a,b);a instanceof B&&a.constructor===B&&a.f===nb?a=a.c:(Na("expected object of type TrustedResourceUrl, got '"+a+"' of type "+Da(a)),a="type_error:TrustedResourceUrl");a=rb.exec(a.toString());b=a[3]||"";return new B(mb,a[1]+sb("?",a[2]||"",c)+sb("#",b,void 0))},nb={},sb=function(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=Array.isArray(e)?e:[e];for(var g=0;g<e.length;g++){var f=e[g];null!=f&&(b||(b=a),b+=
(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(f)))}}return b},mb={};var ub=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},D=function(a,b){return-1!=a.indexOf(b)},vb=function(a,b){return a<b?-1:a>b?1:0};var E=function(a,b){this.c=a===wb&&b||"";this.f=xb};E.prototype.b=!0;E.prototype.a=function(){return this.c.toString()};E.prototype.toString=function(){return"SafeUrl{"+this.c+"}"};var yb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,xb={},wb={};var F;a:{var zb=u.navigator;if(zb){var Ab=zb.userAgent;if(Ab){F=Ab;break a}}F=""};var Bb=function(a){Bb[" "](a);return a};Bb[" "]=Ca;var Cb=function(a,b){try{return Bb(a[b]),!0}catch(c){}return!1},Eb=function(a,b){var c=Db;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Fb=D(F,"Opera"),G=D(F,"Trident")||D(F,"MSIE"),Gb=D(F,"Edge"),Hb=D(F,"Gecko")&&!(D(F.toLowerCase(),"webkit")&&!D(F,"Edge"))&&!(D(F,"Trident")||D(F,"MSIE"))&&!D(F,"Edge"),Ib=D(F.toLowerCase(),"webkit")&&!D(F,"Edge"),Jb=function(){var a=u.document;return a?a.documentMode:void 0},Kb;
a:{var Lb="",Mb=function(){var a=F;if(Hb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Gb)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ib)return/WebKit\/(\S+)/.exec(a);if(Fb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Mb&&(Lb=Mb?Mb[1]:"");if(G){var Nb=Jb();if(null!=Nb&&Nb>parseFloat(Lb)){Kb=String(Nb);break a}}Kb=Lb}
var Ob=Kb,Db={},Pb=function(a){return Eb(a,function(){for(var b=0,c=ub(String(Ob)).split("."),d=ub(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var f=c[g]||"",h=d[g]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;b=vb(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||vb(0==f[2].length,0==h[2].length)||vb(f[2],h[2]);f=f[3];h=h[3]}while(0==b)}return 0<=b})},Qb;
if(u.document&&G){var Rb=Jb();Qb=Rb?Rb:parseInt(Ob,10)||void 0}else Qb=void 0;var Sb=Qb;Object.freeze&&Object.freeze([]);var Tb=document;var Ub=Object.freeze||function(a){return a};var Vb=function(a,b,c){this.reset(a,b,c,void 0,void 0)};Vb.prototype.a=null;var Wb=0;Vb.prototype.reset=function(a,b,c,d,e){"number"==typeof e||Wb++;d||Ha();delete this.a};var Xb=function(a){this.f=a;this.b=this.c=this.a=null},Yb=function(a,b){this.name=a;this.value=b};Yb.prototype.toString=function(){return this.name};var vc=new Yb("SEVERE",1E3),wc=new Yb("CONFIG",700),xc=new Yb("FINE",500),yc=function(a){if(a.c)return a.c;if(a.a)return yc(a.a);Na("Root logger has no level set.");return null};Xb.prototype.log=function(a,b,c){if(a.value>=yc(this).value)for(v(b)&&(b=b()),a=new Vb(a,String(b),this.f),c&&(a.a=c),c=this;c;)c=c.a};
var zc={},Ac=null,Bc=function(a){Ac||(Ac=new Xb(""),zc[""]=Ac,Ac.c=wc);var b;if(!(b=zc[a])){b=new Xb(a);var c=a.lastIndexOf("."),d=a.substr(c+1);c=Bc(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;zc[a]=b}return b};var H=function(a,b){a&&a.log(xc,b,void 0)};Bc("boq.contributorcommonfccookieweb.fcCookieReader");var Cc=function(a,b){var c;var d=document;b=b||d;if(b.querySelectorAll&&b.querySelector&&a)return b.querySelectorAll(a?"."+a:"");if(a&&b.getElementsByClassName){var e=b.getElementsByClassName(a);return e}e=b.getElementsByTagName("*");if(a){var g={};for(d=c=0;b=e[d];d++){var f=b.className,h;if(h="function"==typeof f.split)h=0<=Pa(f.split(/\s+/),a);h&&(g[c++]=b)}g.length=c;return g}return e},Dc=function(a){this.a=a||u.document||document};
Dc.prototype.appendChild=function(a,b){z(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};var Ec=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Fc=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var Gc=function(a){try{return!!a&&null!=a.location.href&&Cb(a,"foo")}catch(b){return!1}};var Hc=function(){this.j=this.j;this.v=this.v};Hc.prototype.j=!1;Hc.prototype.i=function(){if(this.v)for(;this.v.length;)this.v.shift()()};/*
 *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
*****************************************************************************/
var Ic=function(){var a=void 0===a?u:a;var b=a.context||a.AMP_CONTEXT_DATA;if(!b)try{b=a.parent.context||a.parent.AMP_CONTEXT_DATA}catch(c){}try{if(b&&b.pageViewId&&b.canonicalUrl)return b}catch(c){}return null};var Jc=!!window.google_async_iframe_id,I=Jc&&window.parent||window,Kc=function(){if(Jc&&!Gc(I)){var a="."+Tb.domain;try{for(;2<a.split(".").length&&!Gc(I);)Tb.domain=a=a.substr(a.indexOf(".")+1),I=window.parent}catch(b){}Gc(I)||(I=window)}return I};lb(new A(jb,"//fonts.googleapis.com/css"));var Lc=null;var Mc=function(a,b,c){this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0};var J=u.performance,Nc=!!(J&&J.mark&&J.measure&&J.clearMarks),Oc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a;if(a=Nc){var b;if(null===Lc){Lc="";try{a="";try{a=u.top.location.hash}catch(c){a=u.location.hash}a&&(Lc=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=Lc;a=!!b.indexOf&&0<=b.indexOf("1337")}return a}),Pc=function(){var a=K;this.a=[];this.c=a||u;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.a=a.google_js_reporting_queue,
b=a.google_measure_js_timing);this.b=Oc()||(null!=b?b:1>Math.random())},Qc=function(a){a&&J&&Oc()&&(J.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),J.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))};Pc.prototype.start=function(a,b){if(!this.b)return null;var c=void 0===c?u:c;c=c.performance;(c=c&&c.now?c.now():null)||(c=(c=u.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):Ha());a=new Mc(a,b,c);b="goog_"+a.label+"_"+a.uniqueId+"_start";J&&Oc()&&J.mark(b);return a};var K=Kc(),Rc=new Pc,Sc=function(){K.google_measure_js_timing||(Rc.b=!1,Rc.a!=Rc.c.google_js_reporting_queue&&(Oc()&&Qa(Rc.a,Qc),Rc.a.length=0))};"number"!==typeof K.google_srt&&(K.google_srt=Math.random());if("complete"==K.document.readyState)Sc();else if(Rc.b){var Tc=function(){Sc()},Uc=K;Uc.addEventListener&&Uc.addEventListener("load",Tc,!1)};var Vc=function(){var a=Ic();return(a?Gc(a.master)?a.master:null:null)||Kc()};var L=navigator,Wc=function(){try{return L.javaEnabled()}catch(a){return!1}},Xc=function(a){var b=1,c;if(void 0!=a&&""!=a)for(b=0,c=a.length-1;0<=c;c--){var d=a.charCodeAt(c);b=(b<<6&268435455)+d+(d<<14);d=b&266338304;b=0!=d?b^d>>21:b}return b},Yc=function(a,b){if(!a||"none"==a)return 1;a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return Xc(a.toLowerCase())},Zc=/^\s*_ga=\s*1\.(\d+)[^.]*\.(.*?)\s*$/,$c=/^[^=]+=\s*GA1\.(\d+)[^.]*\.(.*?)\s*$/,ad=/^\s*_ga=\s*()(amp-[\w.-]{22,64})$/;var bd=window;var cd={};var dd=[];function ed(){var a={};var b=bd.google_tag_data;bd.google_tag_data=void 0===b?a:b;a=bd.google_tag_data;a.ics||(a.ics={entries:{},set:fd,update:gd,addListener:hd,notifyListeners:id,active:!1});return a.ics}
function fd(a,b,c,d,e,g){var f=ed();f.active=!0;if(void 0!=b){var h=f.entries;f=h[a]||{};var k=f.region;c=c&&"string"==typeof c?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(c===e||(c===d?k!==e:!c&&!k)){d=!!(g&&0<g&&void 0===f.update);var l={region:c,initial:"granted"===b,update:f.update,quiet:d};h[a]=l;d&&bd.setTimeout(function(){h[a]===l&&l.quiet&&(l.quiet=!1,jd(a),id(),cd.TAGGING=cd.TAGGING||[],cd.TAGGING[2]=!0)},g)}}}
function gd(a,b){var c=ed();c.active=!0;if(void 0!=b){var d=kd(a);c=c.entries;c=c[a]=c[a]||{};c.update="granted"===b;b=kd(a);c.quiet?(c.quiet=!1,jd(a)):b!==d&&jd(a)}}function hd(a,b){dd.push({U:a,$:b})}function jd(a){for(var b=0;b<dd.length;++b){var c=dd[b];"[object Array]"==Object.prototype.toString.call(Object(c.U))&&-1!==c.U.indexOf(a)&&(c.V=!0)}}function id(){for(var a=0;a<dd.length;++a){var b=dd[a];if(b.V){b.V=!1;try{b.$.call()}catch(c){}}}}
var kd=function(a){a=ed().entries[a]||{};return void 0!==a.update?a.update:void 0!==a.initial?a.initial:void 0};var ld={},md=function(){return void 0==ld.gtag_cs_api?!1:ld.gtag_cs_api};var nd=function(){if(!md()||!ed().active)return!0;if((ed().entries.ad_storage||{}).quiet)return!1;var a=kd("ad_storage");return null==a?!0:!!a};var od=/^~?[\w-]+$/,pd=function(a){return a.filter(function(b){return od.test(b)})};var qd=/^UA-\d+-\d+%3A[\w-]+(?:%2C[\w-]+)*(?:%3BUA-\d+-\d+%3A[\w-]+(?:%2C[\w-]+)*)*$/,rd=/^~?[\w-]+(?:\.~?[\w-]+)*$/,sd=/^\d+\.fls\.doubleclick\.net$/,td=/;gac=([^;?]+)/,ud=/;gclaw=([^;?]+)/;var vd;(vd=!G)||(vd=9<=Number(Sb));var wd=vd,xd=G&&!Pb("9"),yd=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",Ca,b),u.removeEventListener("test",Ca,b)}catch(c){}return a}();var zd=function(a,b){this.type=a;this.a=this.target=b;this.defaultPrevented=!1};zd.prototype.b=function(){this.defaultPrevented=!0};var Ad=function(a,b){zd.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.c=null;a&&this.init(a,b)};y(Ad,zd);var Bd=Ub({2:"touch",3:"pen",4:"mouse"});
Ad.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;(b=a.relatedTarget)?Hb&&(Cb(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:
a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Bd[a.pointerType]||"";this.c=a;a.defaultPrevented&&this.b()};
Ad.prototype.b=function(){Ad.M.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,xd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Cd="closure_listenable_"+(1E6*Math.random()|0),Dd=0;var Ed=function(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.C=e;this.key=++Dd;this.u=this.A=!1},Fd=function(a){a.u=!0;a.listener=null;a.a=null;a.src=null;a.C=null};var Gd=function(a){this.src=a;this.a={};this.b=0};Gd.prototype.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var f=Hd(a,b,d,e);-1<f?(b=a[f],c||(b.A=!1)):(b=new Ed(b,this.src,g,!!d,e),b.A=c,a.push(b));return b};var Id=function(a,b){var c=b.type;c in a.a&&Ta(a.a[c],b)&&(Fd(b),0==a.a[c].length&&(delete a.a[c],a.b--))},Hd=function(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.u&&g.listener==b&&g.capture==!!c&&g.C==d)return e}return-1};var Jd="closure_lm_"+(1E6*Math.random()|0),Kd={},Ld=0,Nd=function(a,b,c,d,e){if(d&&d.once)return Md(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)Nd(a,b[g],c,d,e);return null}c=re(c);return a&&a[Cd]?se(a,b,c,Ea(d)?!!d.capture:!!d,e):te(a,b,c,!1,d,e)},te=function(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var f=Ea(e)?!!e.capture:!!e,h=ue(a);h||(a[Jd]=h=new Gd(a));c=h.add(b,c,d,f,g);if(c.a)return c;d=ve();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)yd||(e=f),void 0===e&&
(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(we(b.toString()),d);else if(a.addListener&&a.removeListener)z("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ld++;return c},ve=function(){var a=xe,b=wd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Md=function(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)Md(a,
b[g],c,d,e);return null}c=re(c);return a&&a[Cd]?a.c.add(String(b),c,!0,Ea(d)?!!d.capture:!!d,e):te(a,b,c,!0,d,e)},ye=function(a,b,c,d,e){if(Array.isArray(b))for(var g=0;g<b.length;g++)ye(a,b[g],c,d,e);else(d=Ea(d)?!!d.capture:!!d,c=re(c),a&&a[Cd])?(a=a.c,b=String(b).toString(),b in a.a&&(g=a.a[b],c=Hd(g,c,d,e),-1<c&&(Fd(g[c]),z(null!=g.length),Array.prototype.splice.call(g,c,1),0==g.length&&(delete a.a[b],a.b--)))):a&&(a=ue(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Hd(b,c,d,e)),(c=-1<a?b[a]:null)&&ze(c))},
ze=function(a){if("number"!==typeof a&&a&&!a.u){var b=a.src;if(b&&b[Cd])Id(b.c,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(we(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ld--;(c=ue(b))?(Id(c,a),0==c.b&&(c.src=null,b[Jd]=null)):Fd(a)}}},we=function(a){return a in Kd?Kd[a]:Kd[a]="on"+a},Be=function(a,b,c,d){var e=!0;if(a=ue(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.u&&
(g=Ae(g,d),e=e&&!1!==g)}return e},Ae=function(a,b){var c=a.listener,d=a.C||a.src;a.A&&ze(a);return c.call(d,b)},xe=function(a,b){if(a.u)return!0;if(!wd){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new Ad(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(f){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.a;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-
1;0<=e;e--){b.a=d[e];var g=Be(d[e],a,!0,b);c=c&&g}for(e=0;e<d.length;e++)b.a=d[e],g=Be(d[e],a,!1,b),c=c&&g}return c}return Ae(a,new Ad(b,this))},ue=function(a){a=a[Jd];return a instanceof Gd?a:null},Ce="__closure_events_fn_"+(1E9*Math.random()>>>0),re=function(a){z(a,"Listener can not be null.");if(v(a))return a;z(a.handleEvent,"An object listener must have handleEvent method.");a[Ce]||(a[Ce]=function(b){return a.handleEvent(b)});return a[Ce]};var De=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Ee=function(){},Fe=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=
b;b=d.length;c.push("[");for(var e="",g=0;g<b;g++)c.push(e),Fe(a,d[g],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(g=b[d],"function"!=typeof g&&(c.push(e),Ge(d,c),c.push(":"),Fe(a,g,c),e=","));c.push("}");return}}switch(typeof b){case "string":Ge(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;
case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},He={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ie=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,Ge=function(a,b){b.push('"',a.replace(Ie,function(c){var d=He[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),He[c]=d);return d}),'"')};var N=function(){Hc.call(this);this.c=new Gd(this);this.W=this;this.J=null};y(N,Hc);N.prototype[Cd]=!0;N.prototype.addEventListener=function(a,b,c,d){Nd(this,a,b,c,d)};N.prototype.removeEventListener=function(a,b,c,d){ye(this,a,b,c,d)};
N.prototype.dispatchEvent=function(a){Je(this);var b=this.J;if(b){var c=[];for(var d=1;b;b=b.J)c.push(b),z(1E3>++d,"infinite loop")}b=this.W;d=a.type||a;if("string"===typeof a)a=new zd(a,b);else if(a instanceof zd)a.target=a.target||b;else{var e=a;a=new zd(d,b);ib(a,e)}e=!0;if(c)for(var g=c.length-1;0<=g;g--){var f=a.a=c[g];e=Ke(f,d,!0,a)&&e}f=a.a=b;e=Ke(f,d,!0,a)&&e;e=Ke(f,d,!1,a)&&e;if(c)for(g=0;g<c.length;g++)f=a.a=c[g],e=Ke(f,d,!1,a)&&e;return e};
N.prototype.i=function(){N.M.i.call(this);if(this.c){var a=this.c,b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,Fd(d[e]);delete a.a[c];a.b--}}this.J=null};var se=function(a,b,c,d,e){Je(a);return a.c.add(String(b),c,!1,d,e)},Ke=function(a,b,c,d){b=a.c.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,g=0;g<b.length;++g){var f=b[g];if(f&&!f.u&&f.capture==c){var h=f.listener,k=f.C||f.src;f.A&&Id(a.c,f);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented},Je=function(a){z(a.c,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var Le=function(){};Le.prototype.a=null;var Ne=function(a){var b;(b=a.a)||(b={},Me(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Oe,Pe=function(){};y(Pe,Le);var Qe=function(a){return(a=Me(a))?new ActiveXObject(a):new XMLHttpRequest},Me=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.b};Oe=new Pe;var O=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof O)for(c=a.m(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};O.prototype.f=function(){Re(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};O.prototype.m=function(){Re(this);return this.a.concat()};
var Re=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];P(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],P(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};O.prototype.get=function(a,b){return P(this.b,a)?this.b[a]:b};O.prototype.set=function(a,b){P(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};O.prototype.forEach=function(a,b){for(var c=this.m(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
var P=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Se=function(a,b,c){if(v(a))c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:u.setTimeout(a,b||0)};var Q=function(a){N.call(this);this.headers=new O;this.w=a||null;this.f=!1;this.G=this.a=null;this.l=this.O=this.s="";this.g=this.I=this.o=this.H=!1;this.h=0;this.D=null;this.R="";this.F=this.K=!1};y(Q,N);Q.prototype.b=Bc("goog.net.XhrIo");var Te=/^https?$/i,Ue=["POST","PUT"],Ve=[],Xe=function(a,b){var c=new Q;Ve.push(c);b&&se(c,"complete",b);c.c.add("ready",c.X,!0,void 0,void 0);c.h=5E3;c.K=!0;We(c,a);return c};Q.prototype.X=function(){this.j||(this.j=!0,this.i());Ta(Ve,this)};
var We=function(a,b){if(a.a)throw Error("[goog.net.XhrIo] Object is active with another request="+a.s+"; newUri="+b);a.s=b;a.l="";a.O="GET";a.H=!1;a.f=!0;a.a=a.w?Qe(a.w):Qe(Oe);a.G=a.w?Ne(a.w):Ne(Oe);a.a.onreadystatechange=x(a.P,a);try{H(a.b,R(a,"Opening Xhr")),a.I=!0,a.a.open("GET",String(b),!0),a.I=!1}catch(e){H(a.b,R(a,"Error opening Xhr: "+e.message));Ye(a,e);return}b=new O(a.headers);var c=Sa(b.m()),d=u.FormData&&!1;!(0<=Pa(Ue,"GET"))||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
b.forEach(function(e,g){this.a.setRequestHeader(g,e)},a);a.R&&(a.a.responseType=a.R);"withCredentials"in a.a&&a.a.withCredentials!==a.K&&(a.a.withCredentials=a.K);try{Ze(a),0<a.h&&(a.F=$e(a.a),H(a.b,R(a,"Will abort after "+a.h+"ms if incomplete, xhr2 "+a.F)),a.F?(a.a.timeout=a.h,a.a.ontimeout=x(a.T,a)):a.D=Se(a.T,a.h,a)),H(a.b,R(a,"Sending request")),a.o=!0,a.a.send(""),a.o=!1}catch(e){H(a.b,R(a,"Send error: "+e.message)),Ye(a,e)}},$e=function(a){return G&&Pb(9)&&"number"===typeof a.timeout&&void 0!==
a.ontimeout},Ra=function(a){return"content-type"==a.toLowerCase()};Q.prototype.T=function(){"undefined"!=typeof Ba&&this.a&&(this.l="Timed out after "+this.h+"ms, aborting",H(this.b,R(this,this.l)),this.dispatchEvent("timeout"),this.abort(8))};var Ye=function(a,b){a.f=!1;a.a&&(a.g=!0,a.a.abort(),a.g=!1);a.l=b;af(a);bf(a)},af=function(a){a.H||(a.H=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
Q.prototype.abort=function(){this.a&&this.f&&(H(this.b,R(this,"Aborting")),this.f=!1,this.g=!0,this.a.abort(),this.g=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),bf(this))};Q.prototype.i=function(){this.a&&(this.f&&(this.f=!1,this.g=!0,this.a.abort(),this.g=!1),bf(this,!0));Q.M.i.call(this)};Q.prototype.P=function(){this.j||(this.I||this.o||this.g?cf(this):this.Y())};Q.prototype.Y=function(){cf(this)};
var cf=function(a){if(a.f&&"undefined"!=typeof Ba)if(a.G[1]&&4==df(a)&&2==ef(a))H(a.b,R(a,"Local request error detected and ignored"));else if(a.o&&4==df(a))Se(a.P,0,a);else if(a.dispatchEvent("readystatechange"),4==df(a)){H(a.b,R(a,"Request complete"));a.f=!1;try{if(ff(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var b=2<df(a)?a.a.statusText:""}catch(c){H(a.b,"Can not get status: "+c.message),b=""}a.l=b+" ["+ef(a)+"]";af(a)}}finally{bf(a)}}},bf=function(a,b){if(a.a){Ze(a);var c=
a.a,d=a.G[0]?Ca:null;a.a=null;a.G=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){(a=a.b)&&a.log(vc,"Problem encountered resetting onreadystatechange: "+e.message,void 0)}}},Ze=function(a){a.a&&a.F&&(a.a.ontimeout=null);a.D&&(u.clearTimeout(a.D),a.D=null)},ff=function(a){var b=ef(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.s).match(Ec)[1]||null,!a&&u.self&&u.self.location&&(a=u.self.location.protocol,
a=a.substr(0,a.length-1)),b=!Te.test(a?a.toLowerCase():"");c=b}return c},df=function(a){return a.a?a.a.readyState:0},ef=function(a){try{return 2<df(a)?a.a.status:-1}catch(b){return-1}},R=function(a,b){return b+" ["+a.O+" "+a.s+" "+ef(a)+"]"};var W=function(a,b){this.b=this.i=this.f="";this.j=null;this.g=this.a="";this.h=!1;var c;a instanceof W?(this.h=void 0!==b?b:a.h,gf(this,a.f),this.i=a.i,this.b=a.b,hf(this,a.j),this.a=a.a,jf(this,kf(a.c)),this.g=a.g):a&&(c=String(a).match(Ec))?(this.h=!!b,gf(this,c[1]||"",!0),this.i=lf(c[2]||""),this.b=lf(c[3]||"",!0),hf(this,c[4]),this.a=lf(c[5]||"",!0),jf(this,c[6]||"",!0),this.g=lf(c[7]||"")):(this.h=!!b,this.c=new X(null,this.h))};
W.prototype.toString=function(){var a=[],b=this.f;b&&a.push(mf(b,nf,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.i)&&a.push(mf(b,nf,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(mf(c,"/"==c.charAt(0)?of:pf,!0));(c=this.c.toString())&&a.push("?",c);(c=this.g)&&a.push("#",mf(c,qf));return a.join("")};
W.prototype.resolve=function(a){var b=new W(this),c=!!a.f;c?gf(b,a.f):c=!!a.i;c?b.i=a.i:c=!!a.b;c?b.b=a.b:c=null!=a.j;var d=a.a;if(c)hf(b,a.j);else if(c=!!a.a){if("/"!=d.charAt(0))if(this.b&&!this.a)d="/"+d;else{var e=b.a.lastIndexOf("/");-1!=e&&(d=b.a.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(D(e,"./")||D(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],f=0;f<e.length;){var h=e[f++];"."==h?d&&f==e.length&&g.push(""):".."==h?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),d&&
f==e.length&&g.push("")):(g.push(h),d=!0)}d=g.join("/")}else d=e}c?b.a=d:c=""!==a.c.toString();c?jf(b,kf(a.c)):c=!!a.g;c&&(b.g=a.g);return b};
var gf=function(a,b,c){a.f=c?lf(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))},hf=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.j=b}else a.j=null},jf=function(a,b,c){b instanceof X?(a.c=b,rf(a.c,a.h)):(c||(b=mf(b,sf)),a.c=new X(b,a.h))},lf=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},mf=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,tf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},tf=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},nf=/[#\/\?@]/g,pf=/[#\?:]/g,of=/[#\?]/g,sf=/[#\?@]/g,qf=/#/g,X=function(a,b){this.b=this.a=null;this.c=a||null;this.g=!!b},Y=function(a){a.a||(a.a=new O,a.b=0,a.c&&Fc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};X.prototype.add=function(a,b){Y(this);this.c=null;a=uf(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b=Oa(this.b)+1;return this};
var vf=function(a,b){Y(a);b=uf(a,b);P(a.a.b,b)&&(a.c=null,a.b=Oa(a.b)-a.a.get(b).length,a=a.a,P(a.b,b)&&(delete a.b[b],a.c--,a.a.length>2*a.c&&Re(a)))},wf=function(a,b){Y(a);b=uf(a,b);return P(a.a.b,b)};X.prototype.forEach=function(a,b){Y(this);this.a.forEach(function(c,d){Qa(c,function(e){a.call(b,e,d,this)},this)},this)};X.prototype.m=function(){Y(this);for(var a=this.a.f(),b=this.a.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
X.prototype.f=function(a){Y(this);var b=[];if("string"===typeof a)wf(this,a)&&(b=fb(b,this.a.get(uf(this,a))));else{a=this.a.f();for(var c=0;c<a.length;c++)b=fb(b,a[c])}return b};X.prototype.set=function(a,b){Y(this);this.c=null;a=uf(this,a);wf(this,a)&&(this.b=Oa(this.b)-this.a.get(a).length);this.a.set(a,[b]);this.b=Oa(this.b)+1;return this};X.prototype.get=function(a,b){if(!a)return b;a=this.f(a);return 0<a.length?String(a[0]):b};
X.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.m(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.f(d);for(var g=0;g<d.length;g++){var f=e;""!==d[g]&&(f+="="+encodeURIComponent(String(d[g])));a.push(f)}}return this.c=a.join("&")};
var kf=function(a){var b=new X;b.c=a.c;a.a&&(b.a=new O(a.a),b.b=a.b);return b},uf=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},rf=function(a,b){b&&!a.g&&(Y(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(vf(this,d),vf(this,e),0<c.length&&(this.c=null,this.a.set(uf(this,e),gb(c)),this.b=Oa(this.b)+c.length))},a));a.g=b};var xf=[2],yf=void 0,zf=new function(){};zf.refreshPeriod=3E5;zf.refreshDuration=108E5;
var Af=function(){this.autoRefresh=!0},Bf=function(){},Cf=function(){},Df=function(){},Ef=function(){},Ff=function(a){this.a=a},Gf=function(a,b){this.a=a;this.b=b},Hf=function(a){var b=a.a.adData;return null==b?(Z("adData is null"),!1):null==b.cl||null==b.ak?(Z("missing conversion label or advertiser key"),!1):null==a.a.destinationNumber?(Z("no replace number"),!1):!0},If=function(){},Kf=function(a,b,c){var d=this;this.a=b;this.g=b.destinationNumber;this.f=c||new Af;this.c=!1;v(a)?(this.c=!0,this.f.autoRefresh=
!0):null==a&&(a=function(e,g){Jf(d.g,e,g)});this.h=a;this.b=zf},Uf=function(a){var b,c,d,e,g,f,h;return r(function(k){if(1==k.a){if(!Lf(a))return k.return();b=Mf(a);if(null==b)return k.return();c=Nf(b);d=Of(c);e=null===d?Pf(b):d;g=a;return n(k,Qf(e).catch(function(l){Z(l);return zf}),2)}g.b=k.h;f=a.b;Rf(c,e,Date.now()+f.refreshDuration);f.phoneNumber&&f.formattedPhoneNumber&&(h=Sf(f.phoneNumber,a.a.destinationNumber,f.formattedPhoneNumber),Tf(a,h,f.phoneNumber));k.a=0})},Wf=function(a){var b,c,d;
return r(function(e){if(1==e.a)return n(e,Uf(a),2);if(!a.f.autoRefresh)return e.return();b=a.b.refreshPeriod||3E5;c=setInterval(function(){if(!document.hidden||a.c)return Uf(a)},b);d=Nd(document,"visibilitychange",a.i.bind(a));setTimeout(function(){clearInterval(c);ze(d);setTimeout(function(){Vf(a)},2*b)},a.b.refreshDuration||108E5);e.a=0})};Kf.prototype.i=function(){var a=this;return r(function(b){if(document.hidden&&!a.c)return b.return();Vf(a);return b.return(Uf(a))})};
var Lf=function(a){return null==a.a.destinationNumber?(Z("no destination number"),!1):null==a.a.countryNameCode?(Z("no country name code"),!1):v(a.h)||"string"===typeof a.h?!0:(Z("Invalid receiver."),!1)},Mf=function(a){var b=new If;if(null==a.a.adData)var c=null;else{var d=new Gf(a.a,a.f);if(Hf(d)){var e=new Bf,g=d.a.adData;e.ak=g.ak;e.cl=g.cl;e.alloc=d.b&&d.b.alloc;var f=document,h=window.location.href;var k=(h instanceof W?new W(h):new W(h,void 0)).c.get("gclid");e.L=k||"";e.ia=f.referrer;b:{if(sd.test(f.location.host)){var l=
f.location.href.match(ud);if(l&&2==l.length&&l[1].match(rd)){var q=l[1];break b}}else{var w=[];if(f.cookie){var t,C=f.cookie;if(nd()){for(var U=[],V=String(C||document.cookie).split(";"),Zb=0;Zb<V.length;Zb++){var Od=V[Zb].split("="),Pd=Od[0].replace(/^\s*|\s*$/g,"");if(Pd&&"_gcl_aw"==Pd){var hg=Od.slice(1).join("=").replace(/^\s*|\s*$/g,"");U.push(hg)}}var Qd=U}else Qd=[];if((t=Qd)&&0!=t.length){for(var $b=0;$b<t.length;$b++){var Ua=t[$b].split(".");var ig=3==Ua.length&&"GCL"==Ua[0]&&Ua[1]?Ua[2]:
void 0;var Va=ig,ac;if(ac=Va){d:if(Array.prototype.indexOf){var Rd=w.indexOf(Va);var bc="number"==typeof Rd?Rd:-1}else{for(var Wa=0;Wa<w.length;Wa++)if(w[Wa]===Va){bc=Wa;break d}bc=-1}ac=-1===bc}ac&&w.push(Va)}var cc=pd(w)}else cc=w}else cc=w;var Sd=cc;if(0<Sd.length){q=Sd.join(".");break b}}q=""}e.ha=q;if(sd.test(f.location.host)){var Xa=f.location.href.match(td);var Td=Xa&&2==Xa.length&&Xa[1].match(qd)?decodeURIComponent(Xa[1]):""}else{if(md()&&ed().active){var Ud=kd("ad_storage");var Vd=null==
Ud?!0:!!Ud}else Vd=!0;if(Vd){for(var M=[],Wd=f.cookie.split(";"),jg=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,dc=0;dc<Wd.length;dc++){var ec=Wd[dc].match(jg);ec&&M.push({N:ec[1],value:ec[2]})}var Ya={};if(M&&M.length)for(var ha=0;ha<M.length;ha++){var va=M[ha].value.split(".");"1"==va[0]&&3==va.length&&va[1]&&(Ya[M[ha].N]||(Ya[M[ha].N]=[]),Ya[M[ha].N].push({timestamp:va[1],L:va[2]}))}var Xd=Ya}else Xd={};var Yd=Xd;var fc=[],gc;for(gc in Yd){for(var Zd=[],$d=Yd[gc],hc=0;hc<$d.length;hc++)Zd.push($d[hc].L);
fc.push(gc+":"+Zd.join(","))}Td=0<fc.length?fc.join(";"):""}e.ba=Td;c=e}else c=null}b.a=c;if(null==a.a.gaData)var ic=null;else{var ae=new Ff(a.a);var jc=ae.a.gaData;if(null==jc){Z("gaData is null");var kc=!1}else if(null==jc.gaWpid)Z("missing gaWpid"),kc=!1;else{c:{var kg=jc.gaWpid,lc=window._gaUserPrefs;if(lc&&lc.ioo&&lc.ioo()||document.getElementById("__gaOptOutExtension")||!0===window["ga-disable-"+kg])var mc=!0;else{try{var be=window.external;if(be&&"oo"==be._gaUserPrefs){mc=!0;break c}}catch(lg){}mc=
!1}}kc=mc?!1:!0}if(kc){var S=new Ef;S.gaWpid=ae.a.gaData.gaWpid;var ce=0;try{ce=window.history.length}catch(lg){}var mg=ce,de=document.domain,wa=document.cookie,Za=window.screen,ng=document.referrer,og=window;if(Ic())var ee=Kc().gaGlobal||{};else{var nc=Math.round((new Date).getTime()/1E3),oc=og.google_analytics_domain_name,$a="undefined"==typeof oc?Yc("auto",de):Yc(oc,de),pg=-1<wa.indexOf("__utma="+$a+"."),qg=-1<wa.indexOf("__utmb="+$a),pc;if(!(pc=Vc().gaGlobal)){var rg={};pc=Vc().gaGlobal=rg}var p=
pc,fe=!1;if(pg){var qc=wa.split("__utma="+$a+".")[1].split(";")[0].split(".");qg?p.sid=qc[3]+"":p.sid||(p.sid=nc+"");p.vid=qc[0]+"."+qc[1];p.from_cookie=!0}else{p.sid||(p.sid=nc+"");if(!p.vid){fe=!0;var sg=Math.round(2147483647*Math.random()),ge=mg,he,T=[L.appName,L.version,L.language?L.language:L.browserLanguage,L.platform,L.userAgent,Wc()?1:0].join("");if(Za)T+=Za.width+"x"+Za.height+Za.colorDepth;else if(u.java&&u.java.awt){var ie=u.java.awt.Toolkit.getDefaultToolkit().getScreenSize();T+=ie.screen.width+
"x"+ie.screen.height}T=T+wa+(ng||"");for(he=T.length;0<ge;)T+=ge--^he++;p.vid=(sg^Xc(T)&2147483647)+"."+nc}p.from_cookie=!1}if(!p.cid){c:{var ia=oc,je=999;ia&&(ia=0==ia.indexOf(".")?ia.substr(1):ia,je=(""+ia).split(".").length);for(var ke,le=999,ab=wa.split(";"),xa=0;xa<ab.length;xa++){var bb=Zc.exec(ab[xa])||$c.exec(ab[xa])||ad.exec(ab[xa]);if(bb){var rc=bb[1]||0;if(rc==je){var me=bb[2];break c}rc<le&&(le=rc,ke=bb[2])}}me=ke}var ya=me;fe&&ya&&-1!=ya.search(/^\d+\.\d+$/)?(p.vid=ya,p.from_cookie=!0):
ya!=p.vid&&(p.cid=ya)}p.dh=$a;p.hid||(p.hid=Math.round(2147483647*Math.random()));ee=p}var sc=ee;S.aa=sc.cid;S.fa=sc.vid;S.ca=sc.hid;var za=document.location;if(za){var cb=za.pathname||"";"/"!=cb.charAt(0)&&(cb="/"+cb);var ne=za.protocol+"//"+za.hostname+cb+za.search}else ne=void 0;S.da=ne;var oe=document,db=oe.referrer,tc;if(tc=/^(https?|android-app):\/\//i.test(db)){c:{var pe="//"+oe.location.hostname,uc=db.indexOf(pe);if(5==uc||6==uc){var eb=db.charAt(uc+pe.length);if("/"==eb||"?"==eb||""==eb||
":"==eb){var qe=!0;break c}}qe=!1}tc=!qe}var tg=tc?db:void 0;S.ea=tg;ic=S}else ic=null}b.b=ic;if(null==b.a&&null==b.b)return Z("missing call tracking data"),null;b.experimentIDs=(a.f||{}).experimentIDs||xf;b.c=a.a.destinationNumber.replace(/[^0-9A-Z]/gi,"");b.countryNameCode=a.a.countryNameCode;return b},Tf=function(a,b,c){var d=a.h;if(v(d))Xf()||(Z("Sending ",b," to callback"),Yf("success")),d(b,c);else if(d){var e=[],g=document.getElementById(d);g&&e.push(g);(g=document)?(z(g,"Node cannot be null or undefined."),
g=new Dc(9==g.nodeType?g:g.ownerDocument||g.document)):g=Ka||(Ka=new Dc);var f=(g=g.a)||document;g=f.querySelectorAll&&f.querySelector?f.querySelectorAll("."+d):Cc(d,g);for(f=0;f!==g.length;++f)e.push(g[f]);if(0===e.length)Z("Found no elements matching ",d),Yf("receiver not found");else{for(d=0;d!==e.length;d++){for(f=e[d];g=f.firstChild;)f.removeChild(g);e[d].appendChild(document.createTextNode(b));g=Zf(e[d],c);null!==g&&void 0===yf&&(yf=g)}Z("Updated ",e.length," element(s) with ",b);Yf("success")}}a.g=
b},Vf=function(a){!a.c&&yf&&Tf(a,a.a.destinationNumber,yf)},$f=null,ag=!1;
function bg(){var a=document.getElementById("google-wcc-debug-window");if(a)return a;var b=function(d){if("string"===typeof d)return document.createTextNode(d);var e=document.createElement(d[0]);e.setAttribute("style",d[1]+";");if(d[2])for(var g=0;g!==d[2].length;++g)e.appendChild(b(d[2][g]));return e},c=b(["div","background-color:#fafafa;color:#000;border:1px solid #ddd;border-radius:3px;font-family:sans-serif;font-size:13px;position:fixed;bottom:0;left:0;width:40em;display:block;text-align:left;z-index:2147483645",[["div",
"color:#222;font-size:16px;border-bottom:1px solid #ddd;padding:13px",["Google AdWords Website Call Conversions",["span","float:right",[["button","border:1px solid #ddd;background-color:#fff;font-weight:bold;font-size:12px;padding:4px 8px;color:#444;box-shadow:#eee 0px 1px 0px 0px",["Force"]],["button","border:1px solid #ddd;background-color:#fff;font-weight:bold;font-size:12px;padding:4px 8px;color:#444;box-shadow:#eee 0px 1px 0px 0px",["Close"]]]]]],["div","height:10em;padding:10px;overflow-y:auto"]]]);
document.body.appendChild(c);a=c.childNodes[0].childNodes[1].childNodes;a[0].onclick=function(){return r(function(d){if($f){var e=$f;var g=e.g.replace(/\d/g,"9");g=["+"+g.replace(/[^0-9]/g,""),g];var f=ba(g);g=f.next().value;f=f.next().value;Tf(e,f,g)}d.a=0})};a[1].onclick=function(){c.style.display="none"};a=c.childNodes[1];a.id="google-wcc-debug-window";return a}
function Z(a){if(ag){for(var b="",c=0;c!==arguments.length;++c){if("string"!==typeof arguments[c]){var d=arguments,e=c,g=[];Fe(new Ee,arguments[c],g);d[e]=g.join("")}b+=arguments[c]}""!==b&&("."!==b[b.length-1]&&(b+="."),c=bg(),c.appendChild(document.createTextNode(b)),c.appendChild(document.createElement("br")))}}function Nf(a){var b=[];a.a&&b.push(a.a.cl);a.b&&b.push(a.b.gaWpid);b.push(a.c);return b.join(",")}
function Of(a){var b=window.localStorage.getItem(a+"_expiresAt");return null==b||Number(b)<Date.now()?null:window.localStorage.getItem(a)}function Rf(a,b,c){var d=window.localStorage,e=d.getItem(a+"_expiresAt");if(null==e||Number(e)<Date.now())d.setItem(a+"_expiresAt",c.toString()),d.setItem(a,b)}
function Pf(a){var b=a.b||{},c=a.a||{},d={cc:a.countryNameCode,dn:a.c,ga_wpid:b.gaWpid,ga_vid:b.fa,ga_hid:b.ca,ga_cid:b.aa,ga_loc:b.da,ga_ref:b.ea,cl:c.cl,alloc:c.alloc,gclid:c.L,ref:c.ia,gac:c.ba,gclaw:c.ha,ct_eid:(a.experimentIDs||[]).join()};Object.keys(d).forEach(function(e){return!d[e]&&delete d[e]});return a.a?tb(new A(jb,"https://www.googleadservices.com/pagead/conversion/%{ak}/wcm"),{ak:c.ak},d).a():tb(new A(jb,"https://www.googleadservices.com/ga/phone"),{},d).a()}
function Qf(a){return new Promise(function(b,c){se(Xe(a,function(d){if(ff(d.target)&&200==ef(d.target)){d=d.target;if(d.a)b:{d=d.a.responseText;if(u.JSON)try{var e=u.JSON.parse(d);z("object"==typeof e);var g=e;break b}catch(f){}g=De(d)}else g=void 0;b(g)}else c("request phone number failure")}),"timeout",function(){c("request timeout")})})}
function cg(a){if(a=!window.google_no_debug&&(!a||!a.noDebug))a=window.location.hash,a=a.startsWith("#google-wcc-")||a.startsWith("#google-phone-")||"undefined"!==typeof window.sessionStorage&&"y"===window.sessionStorage.getItem("_goog_wcc_debug");ag=a}function Xf(){var a=window.google_replace_number;return"string"===typeof a&&0<a.length}function Yf(a){window.google_wcc_status=a}
function Sf(a,b,c){if(a.match(/^\+1\d{10}$/)){var d=b.match(/\d/g);d=d?d.length:0;if(10!==d&&11!==d)b=null;else{d=11===d?1:2;for(var e="",g=0;g!==b.length;++g)e=b.charAt(g).match(/\d/)?e+a.charAt(d++):e+b.charAt(g);b=e}}else b=null;return b?b:c?c:a}
function Zf(a,b){a:{for(;null!=a;a=a.parentNode)if("A"===a.nodeName){if(a.href&&"tel:"===a.href.substr(0,4))break a;break}a=null}if(null!=a){var c=a.href.slice(4);b="tel:"+b;var d=String(b.substr(0,4)).toLowerCase();0==("tel:"<d?-1:"tel:"==d?0:1)||(b="about:invalid#zClosurez");b=new E(wb,b);a:{try{var e=a&&a.ownerDocument,g=e&&(e.defaultView||e.parentWindow);g=g||u;if(g.Element&&g.Location){var f=g;break a}}catch(k){}f=null}if(f&&"undefined"!=typeof f.HTMLAnchorElement&&(!a||!(a instanceof f.HTMLAnchorElement)&&
(a instanceof f.Location||a instanceof f.Element))){if(Ea(a))try{var h=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(k){h="<object could not be stringified>"}else h=void 0===a?"undefined":null===a?"null":typeof a;Na("Argument is not a %s (or a non-Element, non-Location mock); got: %s","HTMLAnchorElement",h)}b instanceof E?f=b:(f=b,f instanceof E||(f="object"==typeof f&&f.b?f.a():String(f),z(yb.test(f),"%s does not match the safe URL pattern",f)||(f="about:invalid#zClosurez"),
f=new E(wb,f)));f instanceof E&&f.constructor===E&&f.f===xb?f=f.c:(Na("expected object of type SafeUrl, got '"+f+"' of type "+Da(f)),f="type_error:SafeUrl");a.href=f;return c}return null}
function dg(a,b,c){var d=function(e){if(1===e.nodeType&&("SCRIPT"===e.nodeName||"google-wcc-debug-window"===e.id))return 0;var g=0;if(3===e.nodeType&&-1!==e.data.search(a)){e.data=e.data.replace(a,b);var f=Zf(e,c);null!==f&&void 0===yf&&(yf=f);++g}e=e.childNodes;for(f=0;f!==e.length;f++)g+=d(e[f]);return g};return d(document.body)}
function Jf(a,b,c){var d=10,e=a.replace(/[^0-9]/g,"");if(0===e.length)Z('The specified number "',a,'" cannot be replaced'),Yf("autoreplace fail");else{var g=new RegExp("\\(?"+e.split("").join("[^0-9]{0,3}"),"g"),f=function(){var h=dg(g,b,c);if(0<h){if(Z("Updated ",h," element(s) with ",b),Yf("success"),"loading"===document.readyState){var k=function(){"complete"===document.readyState?dg(g,b,c):Md(document,"readystatechange",k)};Md(document,"readystatechange",k)}}else 0<d--?setTimeout(f,500):(Z("Could not find ",
a," in the page"),Yf("autoreplace fail"))};f()}}function eg(a,b,c,d,e,g,f){var h;return r(function(k){cg(f);Xf()||c.autoreplace?Z("Attempting to auto-replace"):v(b)?Z("Using callback as target"):"string"===typeof b&&Z("Using CSS class '",b,"' as target");e&&clearTimeout(e);h=new Df;h.adData=c;h.destinationNumber=d||c.autoreplace;h.countryNameCode="ZZ";return n(k,fg(b,h,f),0)})}
function gg(a,b,c){var d;return r(function(e){if(null==c.ga_wpid)return e.return();d=new Df;d.destinationNumber=c.replace||c.destination;d.countryNameCode="US";d.gaData=new Cf;d.gaData.gaWpid=c.ga_wpid;return n(e,fg(c.receiver,d,null),0)})}function fg(a,b,c){var d;return r(function(e){cg(c);$f=d=new Kf(a,b,c);return n(e,Wf(d),0)})}
window._googWcmImpl&&function(){var a,b;return r(function(c){if(1==c.a){a=window._googWcmImpl.q;if(!a){c.a=0;return}b=0}if(4!=c.a)return b===a.length?(c.a=0,c=void 0):c=n(c,eg.apply(void 0,[].slice.apply(a[b])),4),c;++b;c.a=3})}();window._googCallTrackingImpl&&function(){var a,b;return r(function(c){if(1==c.a){a=window._googCallTrackingImpl.q;if(!a){c.a=0;return}b=0}if(4!=c.a)return b===a.length?(c.a=0,c=void 0):c=n(c,fg.apply(void 0,[].slice.apply(a[b])),4),c;++b;c.a=3})}();
window._gaPhoneImpl&&function(){var a,b;return r(function(c){if(1==c.a){a=window._gaPhoneImpl.q;if(!a){c.a=0;return}b=0}if(4!=c.a)return b===a.length?(c.a=0,c=void 0):c=n(c,gg.apply(void 0,[].slice.apply(a[b])),4),c;++b;c.a=3})}();Ia("_googWcmImpl",eg);
Ia("_googWccDebug",function(a){if("undefined"===typeof window.sessionStorage)return"WCC debugging not available.";"enable"===a?window.sessionStorage.setItem("_goog_wcc_debug","y"):"disable"===a&&window.sessionStorage.removeItem("_goog_wcc_debug");return"WCC debugging is "+("y"===window.sessionStorage.getItem("_goog_wcc_debug")?"enabled.":"disabled.")});Ia("_googCallTrackingImpl",fg);Ia("_gaPhoneImpl",gg);if(Xf()){var ug=window.google_replace_number;window._googWcmGet(function(a,b){Jf(ug,a,b)},ug)};}).call(this);
