name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get repo
      run: |
        git clone https://github.com/KTibow/ktibow.github.io.git ./
    - name: Generate sitemap
      run: |
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > old_sitemap.txt
        echo =====================
        cat old_sitemap.txt
        echo generating
        sh generate_sitemap.sh > sitemap.txt
        echo =====================
        cat sitemap.txt
    - name: Submit sitemap
      env:
        token:  ${{ secrets.BING_WEBMASTER_SITEMAP_TOKEN }}
        cookies: ${{ secrets.BING_WEBMASTER_SITEMAP_COOKIES }}
        body: ${{ secrets.BING_WEBMASTER_SITEMAP_BODY }}
      run: |
        mkdir artifacts
        curl -X POST -d "$body" -b "$cookies" https://www.bing.com/webmaster/configure/sitemaps/addsitemap?url=https%3A%2F%2Fktibow.github.io%2F > ./artifacts/webmaster.html
        #curl https://www.bing.com/ping?sitemap=https://ktibow.github.io/sitemap.txt
    - uses: actions/upload-artifact@master
      with:
        name: Sitemap upload response
        path: ./artifacts
    - name: Commit changes
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git add -A
        git commit -m "Add new sitemap" -a || true
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  audit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        run: |
          git clone https://github.com/KTibow/ktibow.github.io.git ./
      - name: Audit URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://ktibow.github.io'
      - name: Upload results
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse report
          path: './report'
      - name: Commit changes
        run: |
          git config --local user.email "KTibow@users.noreply.github.com"
          git config --local user.name "KTibow"
          git add -A
          git commit -m "Add new sitemap" -a || true
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

