name: CI

on: push

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repo
      run: |
        git clone https://github.com/KTibow/ktibow.github.io.git ./
    - name: Update package sources
      run: sudo apt-get update
    - name: Check for valid commit
      run: |
        sudo apt-get install jq
        message=$(curl https://api.github.com/repos/KTibow/ktibow.github.io/git/commits/${{ github.sha }} | jq '.message')
        message="${message%\"}"
        message="${message#\"}"
        bash check-if-works.sh "$message"
    - name: Generate sitemap and commit
      run: |
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > old_sitemap.txt
        sh generate_sitemap.sh > sitemap.txt
        python3 sitemapxml.py
        rm old_sitemap.txt
        rm sitemap.txt
    - name: Commit changes
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git add -A
        git commit -m "Add new sitemap" -a || true
        git pull
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Audit pages
      run: |
        sudo apt-get install chromium-browser
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g lighthouse
        bash lighthouse_report.sh
    - name: Find my report at https://ktibow.github.io/lighthouse/
      run: |
        python3 analyzer.py > lighthouse/index.html
    - name: Commit changes
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git add -A
        git commit -m "Add Lighthouse digest" -a || true
        git pull
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Tell me the build finished
      uses: screendriver/ifttt-action@v1.0.0
      with:
        event: buildfinished
        key:  ${{ secrets.IFTTT_KEY }}
    - name: Go back
      run: |
        cd /home/runner
        sudo chmod 755 .config
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    - name: Submit sitemap
      uses: atymic/sitemap-ping-action@1.0.0
      with:
        # Root sitemap URL
        sitemap-url: https://ktibow.github.io/sitemap.xml
