name: Sitemap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate sitemap.txt
      run: |
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > sitemap.txt
        echo generating
        sh generate_sitemap.sh > sitemap.txt
        echo here it is
        cat sitemap.txt
