name: Sitemap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Generate sitemap
      run: |
        git clone https://github.com/KTibow/ktibow.github.io.git ./
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > sitemap.txt
        echo generating
        sh generate_sitemap.sh > new_sitemap.txt
        echo =====================
        cat new_sitemap.txt
        git switch -
