name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo one line
    - name: Run a multi-line script
      run: |
        mkdir myDir
        ls
