name: Sitemap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get repo
      run: |
        git init "/home/runner/work/ktibow.github.io/ktibow.github.io"
        git remote add origin https://github.com/KTibow/ktibow.github.io
        git config gc.auto 0
        git config --get-all http.https://github.com/KTibow/ktibow.github.io.extraheader
        git config --get-all http.proxy
        git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/*
    - name: Generate sitemap
      run: |
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > sitemap.txt
        echo generating
        sh generate_sitemap.sh > new_sitemap.txt
        echo =====================
        cat new_sitemap.txt
    - name: Commit files
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git commit -m "Add sitemap" -a
    - name: Push sitemap
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      

