name: CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get repo and remove action
      run: |
        git clone https://github.com/KTibow/ktibow.github.io.git ./
        sudo rm -r actions || true
    - name: Change Lighthouse page
      run: |
        mv lighthouse.html old_lighthouse.html || true
        cp preparing_lighthouse.html lighthouse.html || true
    - name: Commit changes
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git add -A
        git commit -m "Change Lighthouse page" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate sitemap
      run: |
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > old_sitemap.txt
        echo =====================
        cat old_sitemap.txt
        echo generating
        sh generate_sitemap.sh > sitemap.txt
        echo =====================
        cat sitemap.txt
    - name: Submit sitemap
      env:
        cookies: ${{ secrets.BING_WEBMASTER_SITEMAP_COOKIES }}
        body: ${{ secrets.BING_WEBMASTER_SITEMAP_BODY }}
      run: |
        curl -X POST -d "$body" -b "$cookies" https://www.bing.com/webmaster/configure/sitemaps/addsitemap?url=https%3A%2F%2Fktibow.github.io%2F > /dev/null
    - name: Commit changes
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git add -A
        git commit -m "Add new sitemap and cached action" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Remove files/folders
      run: |
        rm -r results || true
        rm lighthouse.html || true
    - name: Audit URL
      run: |
        echo =========================================================
        echo updating package sources
        sudo apt-get update
        echo =========================================================
        echo installing chromium
        sudo apt-get install chromium-browser
        echo =========================================================
        echo installing node
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get install -y nodejs
        echo =========================================================
        echo getting lighthouse
        sudo npm install -g lighthouse
        echo =========================================================
        echo "here's the report"
        lighthouse --chrome-flags="--headless" https://ktibow.github.io/
    - name: Find my report at https://ktibow.github.io/lighthouse.html
      run: |
        rm old_lighthouse.html || true
        cp finished_lighthouse.html old_lighthouse.html || true
    - name: Commit changes
      run: |
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git add -A
        git commit -m "Add Lighthouse report" -a || true
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Tell me the build finished
      uses: screendriver/ifttt-action@v1.0.0
      with:
        event: buildfinished
        key:  ${{ secrets.IFTTT_KEY }}


