name: Sitemap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate sitemap
      run: |
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > sitemap.txt
        echo generating
        sh generate_sitemap.sh > new_sitemap.txt
        echo =====================
        cat new_sitemap.txt
        length = `wc -l newsitemap.txt`
        echo $length
