name: Sitemap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get repo
      run: |
        git clone https://github.com/KTibow/ktibow.github.io.git ./
    - name: Generate sitemap
      run: |
        echo running
        find . | grep -v ".*/\..*" | awk 'BEGIN{FIELDWIDTHS="1 1000"}{print $2}' > sitemap.txt
        echo generating
        sh generate_sitemap.sh > sitemap.txt
        echo =====================
        cat new_sitemap.txt
    - name: Commit files
      run: |
        git add .
        git config --local user.email "KTibow@users.noreply.github.com"
        git config --local user.name "KTibow"
        git commit -m "Add sitemap" -a
    - name: Push sitemap
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      

